input{
  beats { port => 5044 }
}

filter {

  # Wazuh Alerts 
  if [log][file][path] == "/var/ossec/logs/alerts/alerts.json" {

    json { source => "message" }

    date {
      match  => [ "timestamp", "yyyy-MM-dd'T'HH:mm:ss.SSSZ" ]
      target => "@timestamp"
    }

    mutate { remove_field => ["message"] }
  }

  # Wazuh Events 
  else if [log][file][path] == "/var/ossec/logs/archives/archives.json" {

    json { source => "message" }

    # Only attempt date parsing if timestamp exists
    if [timestamp] {
      date {
        match => [
          "timestamp",
          "ISO8601",
          "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
          "yyyy-MM-dd HH:mm:ss"
        ]
        target => "@timestamp"
      }
    }

    mutate { remove_field => ["message"] }
  }

  # OCI LOGS
  else if "oci_logs" in [tags] {

    json {
      source => "message"
      target => "oci"
    }

    if [oci][data][identity][ipAddress] {
      mutate {
        add_field => {
          "[source][ip]" => "%{[oci][data][identity][ipAddress]}"
          "srcip"        => "%{[oci][data][identity][ipAddress]}"
        }
      }
    }

    if [oci][data][identity][principalName] {
      mutate {
        add_field => {
          "[user][name]" => "%{[oci][data][identity][principalName]}"
        }
      }
    }

    if [oci][data][eventName] {
      mutate {
        add_field => {
          "[event][action]" => "%{[oci][data][eventName]}"
        }
      }
    }

    if [oci][data][response][status] {
      mutate {
        add_field => {
          "[event][outcome]" => "%{[oci][data][response][status]}"
        }
      }
    }

    mutate {
      add_field => {
        "event.dataset"    => "oci.audit"
        "observer.vendor"  => "Oracle"
        "observer.type"    => "cloud"
        "observer.product" => "OCI"
        "cloud.provider"   => "oci"
        "integration"      => "oci"
      }
      remove_field => ["message"]
    }
  }
}

output {

  if [log][file][path] == "/var/ossec/logs/alerts/alerts.json" {
    elasticsearch {
      hosts    => ["https://127.0.0.1:9200"]
      user     => ***********
      password => ***********
      cacert  => "/etc/kibana/http_ca.crt"
      index   => "wazuh-alerts-%{+YYYY.MM.dd}"
    }
    opensearch {
      hosts => ["https://127.0.0.1:9201"]
      user  => ************
      password => ************
      ssl => true
      cacert => "/etc/logstash/certs/wazuh-root-ca.pem"
      index => "wazuh-alerts-%{+YYYY.MM.dd}"
    }
  }

  else if [log][file][path] == "/var/ossec/logs/archives/archives.json" {
    elasticsearch {
      hosts    => ["https://127.0.0.1:9200"]
      user     => ************
      password => ************
      cacert  => "/etc/kibana/http_ca.crt"
      index   => "wazuh-events-%{+YYYY.MM.dd}"
    }
    opensearch {
      hosts => ["https://127.0.0.1:9201"]
      user  => ************
      password => ************
      ssl => true
      cacert => "/etc/logstash/certs/wazuh-root-ca.pem"
      index => "wazuh-events-%{+YYYY.MM.dd}"
    }
  }

  else if "oci_logs" in [tags] {
    elasticsearch {
      hosts    => ["https://127.0.0.1:9200"]
      user     => ************
      password => ************
      cacert  => "/etc/kibana/http_ca.crt"
      index   => "wazuh-logs-oci-%{+YYYY.MM.dd}"
    }
    opensearch {
      hosts => ["https://127.0.0.1:9201"]
      user  => ************
      password => ************
      ssl => true
      cacert => "/etc/logstash/certs/wazuh-root-ca.pem"
      index => "wazuh-logs-oci-%{+YYYY.MM.dd}"
    }
  }
}
